function(find_vcpkg_root)
    IF(NOT DEFINED VCPKG_ROOT)
        # 强制优先使用项目本地的 vcpkg，避免环境污染
        set(LOCAL_VCPKG_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg")
        IF(EXISTS "${LOCAL_VCPKG_ROOT}/vcpkg.exe" OR EXISTS "${LOCAL_VCPKG_ROOT}/vcpkg")
            set(VCPKG_ROOT ${LOCAL_VCPKG_ROOT} PARENT_SCOPE)
            message(STATUS "使用项目本地 vcpkg: ${LOCAL_VCPKG_ROOT}")
            return()
        ENDIF()
        
        # 如果没有本地 vcpkg，再查找系统的 vcpkg
        IF(WIN32)
            set(VCPKG_PATH_FILE "$ENV{LOCALAPPDATA}/vcpkg/vcpkg.path.txt")
        ELSE()
            set(VCPKG_PATH_FILE "$ENV{HOME}/.vcpkg/vcpkg.path.txt")
        ENDIF()
        IF(EXISTS ${VCPKG_PATH_FILE})
            file(READ ${VCPKG_PATH_FILE} VCPKG_ROOT)
            set(VCPKG_ROOT ${VCPKG_ROOT} PARENT_SCOPE)
            IF(DEFINED ENV{VCPKG_ROOT})
                message(WARNING "vcpkg integration file precedes the VCPKG_ROOT environment variable. To override this, set the VCPKG_ROOT CMake variable")
            ENDIF()
        ELSEIF(DEFINED ENV{VCPKG_ROOT})
            set(VCPKG_ROOT $ENV{VCPKG_ROOT} PARENT_SCOPE)
        ENDIF()
    ENDIF()
endfunction()

IF(WIN32)
    set(MESHLIB_USE_VCPKG_DEFAULT ON)
ELSE()
    set(MESHLIB_USE_VCPKG_DEFAULT OFF)
ENDIF()
option(MESHLIB_USE_VCPKG "Use the vcpkg package manager" ${MESHLIB_USE_VCPKG_DEFAULT})
IF(MESHLIB_USE_VCPKG)
    IF(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        find_vcpkg_root()
        IF(DEFINED VCPKG_ROOT)
            message(STATUS "Found vcpkg: ${VCPKG_ROOT}")
            set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE PATH "CMake toolchain file")
        ELSE()
            message(FATAL_ERROR "vcpkg not found")
        ENDIF()
    ENDIF()

    IF(NOT DEFINED VCPKG_TARGET_TRIPLET)
        # TODO: triplet for Linux and macOS
        set(VCPKG_TARGET_TRIPLET "x64-windows-meshlib" CACHE STRING "vcpkg target triplet")
    ENDIF()
    message(STATUS "Using vcpkg triplet: ${VCPKG_TARGET_TRIPLET}")
ELSEIF(MESHLIB_USE_VCPKG_DEFAULT)
    message(WARNING "vcpkg is disabled explicitly")
ENDIF()